spring.application.name=API-GATEWAY
server.port=8765
spring.profiles.active=local

spring.cloud.gateway.discovery.locator.enabled=true

jwt.secret=supersecretkeythatisverylong123456

logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.com.example.api_gateway=DEBUG

