eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

PROFILE_SERVICE_URL=http://localhost:8090
FLIGHT_SERVICE_URL=http://localhost:8085
BOOKING_SERVICE_URL=http://localhost:8080
FARE_SERVICE_URL=http://localhost:8095
