eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/
eureka.instance.prefer-ip-address=true

PROFILE_SERVICE_URL=lb://PROFILEMANAGEMENT-SERVICE
FLIGHT_SERVICE_URL=lb://FLIGHT-AND-SEARCH-SERVICE
BOOKING_SERVICE_URL=lb://BOOKING-SERVICE
FARE_SERVICE_URL=lb://FARE-SERVICE
