spring.application.name=booking-service
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/bookingdatabase?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Circuit Breaker
resilience4j.circuitbreaker.instances.FLIGHT-AND-SEARCH-SERVICE.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.FLIGHT-AND-SEARCH-SERVICE.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.FLIGHT-AND-SEARCH-SERVICE.failureRateThreshold=50
resilience4j.circuitbreaker.instances.FLIGHT-AND-SEARCH-SERVICE.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.FLIGHT-AND-SEARCH-SERVICE.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.FLIGHT-AND-SEARCH-SERVICE.waitDurationInOpenState=6s
resilience4j.circuitbreaker.instances.FLIGHT-AND-SEARCH-SERVICE.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.FLIGHT-AND-SEARCH-SERVICE.slidingWindowSize=10
resilience4j.circuitbreaker.instances.FLIGHT-AND-SEARCH-SERVICE.slidingWindowType=COUNT_BASED

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

#Actuator
management.endpoints.web.exposure.include=health,info,circuitbreakers
management.endpoints.health.show-details=always
